const express = require("express")
const bodyParser = require("body-parser")
const cors = require("cors")
const morgan = require("morgan")
const { response } = require("express")
const axios = require("axios")
const app = express()
const api = require('./api.js')

// TODO: Get rid of CORS, not necessary as front-/backend of same server
// TODO: Use some tooling to create documentation for our public REST API
////////////////////////////////////////////////////////////////////////////////
// WEB APPLICATION SETUP
////////////////////////////////////////////////////////////////////////////////
app.use(morgan("combined"))
app.use(bodyParser.json())
app.use(cors())

////////////////////////////////////////////////////////////////////////////////
// WEB APPLICATION START
////////////////////////////////////////////////////////////////////////////////
app.listen(process.env.PORT || 8181, "localhost")

// TODO: Implement method stubs: Connect to db (rdflib, MongoDB, etc.) and query
////////////////////////////////////////////////////////////////////////////////
/// PUBLIC REST API
////////////////////////////////////////////////////////////////////////////////
app.get('/api/query/statistics/Files', (_, res) => {
    res.send({message: 'Count', count:1337})
})

app.get('/api/query/statistics/Projects', (_, res) => {
    res.send({message: 'Count', count:31331337})
})

app.get('/api/query/statistics/Usage', (_, res) => {
    res.send({message: 'Count', count:-100})
})

// TODO: Not real JSON but an array of javascript objects. Convert to JSON!
fake_data_gdp = `
[
{ country: 'P01', value: 5 },
{ country: 'P02', value: 13.4 },
{ country: 'P03', value: 4.0 },
{ country: 'P08', value: 4.9 },
{ country: 'P14', value: 2.8 },
{ country: 'Z01', value: 4.8 }
]
`
// Note: This is real (linted) JSON data
fake_data_graph = `
{
  "nodes":[
		{"id":"P01","group":1},
		{"id":"P02","group":2},
		{"id":"P03","group":3},
		{"id":"P04","group":4},
		{"id":"P05","group":5},
		{"id":"P06","group":6},
		{"id":"P07","group":7},
		{"id":"P08","group":8},
		{"id":"P09","group":9},
		{"id":"P10","group":10},
		{"id":"P11","group":11},
		{"id":"P12","group":12},
		{"id":"P13","group":13},
		{"id":"P14","group":14},
		{"id":"P15","group":15},
		{"id":"P16","group":16},
		{"id":"P17","group":17},
		{"id":"P18","group":18}
	],
	"links":[
		{"source":"P01","target":"P03","value":1},
		{"source":"P02","target":"P04","value":3},
		{"source":"P03","target":"P04","value":10},
		{"source":"P01","target":"P04","value":20},
		{"source":"P05","target":"P04","value":1},
		{"source":"P06","target":"P04","value":1},
		{"source":"P06","target":"P04","value":1},
		{"source":"P07","target":"P02","value":1},
		{"source":"P06","target":"P03","value":1},
		{"source":"P04","target":"P07","value":1},
		{"source":"P01","target":"P18","value":1},
		{"source":"P01","target":"P17","value":1},
		{"source":"P07","target":"P09","value":1},
		{"source":"P07","target":"P12","value":1},
		{"source":"P07","target":"P18","value":1},
		{"source":"P07","target":"P13","value":5},
		{"source":"P17","target":"P14","value":3},
		{"source":"P17","target":"P15","value":1},
		{"source":"P12","target":"P08","value":10},
		{"source":"P12","target":"P10","value":1},
		{"source":"P10","target":"P16","value":1},
		{"source":"P16","target":"P11","value":5}
	]
}
`
app.get('/api/query/statistics/MyGDP', (_, res) => {
    // res.send(fake_data_gdp)

	const fs = require('fs')
	// TODO: change this to location on server for file statistics
	fs.readFile('/home/stephan/test_data.txt', 'utf8' , (err, data) => {
	  if (err) {
	    console.error(err)
		res.send(fake_data_gdp)
	    return
	  }
	  console.log(JSON.parse(data).projects)
	  res.send(JSON.parse(data).projects)
	})
})

app.get('/api/query/statistics/Graph', (_, res) => {
    /// TODO: Populate with actual JSON data from db query (rdflib, MongoDB, etc.)
    /// The graph representation can be generated by SPARQL CONSTRUCT queries,
    /// which return data triples (from triple store) and can be converted to
    /// proper JSON before being sent to the frontend application layer
	/// TODO: Populate in the same way from server as MyGDP statistics above
    res.send(fake_data_graph)
})

////////////////////////////////////////////////////////////////////////////////
// INTERNAL USAGE OF REST API FOR WEB APPLICATION
////////////////////////////////////////////////////////////////////////////////
app.post('/register', (req, res) => {
    res.send({ message: `User ${req.body.email} was registered!`})
})

app.post('/query', (req, res) => {
    var type = req.body.queryType;

    if (type == 'MyGDP') {
      axios.get(`http://localhost:8181/api/query/statistics/${type}`).then(function (myrespo) {
        res.send(myrespo.data)
      })
    } else if (type == 'Graph') {
      axios.get(`http://localhost:8181/api/query/statistics/${type}`).then(function (myrespo) {
        res.send(myrespo.data)
        })
    } else {
        axios.get(`http://localhost:8181/api/query/statistics/${type}`).then(function (myrespo) {
            res.send({ message: `Statistics of ${req.body.queryType} have been requested`, 
              mydata: myrespo.data.count})})
    }
})
